name: math_package
description: A package for all oyur arithmatic operations.
version: 1.0.0
repository: https://github.com/aanaltrivedi18/flutter_math_package

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
